Merge 6.6.37 into android15-6.6-lts
Changes in 6.6.37
	iio: pressure: fix some word spelling errors
	iio: pressure: bmp280: Fix BMP580 temperature reading
	usb: typec: ucsi: Never send a lone connector change ack
	usb: typec: ucsi: Ack also failed Get Error commands
	Input: ili210x - fix ili251x_read_touch_data() return value
	pinctrl: fix deadlock in create_pinctrl() when handling -EPROBE_DEFER
	pinctrl: rockchip: fix pinmux bits for RK3328 GPIO2-B pins
	pinctrl: rockchip: fix pinmux bits for RK3328 GPIO3-B pins
	pinctrl: rockchip: use dedicated pinctrl type for RK3328
	pinctrl: rockchip: fix pinmux reset in rockchip_pmx_set
	MIPS: pci: lantiq: restore reset gpio polarity
	selftests: mptcp: print_test out of verify_listener_events
	selftests: mptcp: userspace_pm: fixed subtest names
	wifi: mac80211: Use flexible array in struct ieee80211_tim_ie
	ASoC: rockchip: i2s-tdm: Fix trcm mode by setting clock on right mclk
	ASoC: mediatek: mt8183-da7219-max98357: Fix kcontrol name collision
	ASoC: atmel: convert not to use asoc_xxx()
	ASoC: atmel: atmel-classd: Re-add dai_link->platform to fix card init
	workqueue: Increase worker desc's length to 32
	ASoC: q6apm-lpass-dai: close graph on prepare errors
	bpf: Add missed var_off setting in set_sext32_default_val()
	bpf: Add missed var_off setting in coerce_subreg_to_size_sx()
	s390/pci: Add missing virt_to_phys() for directed DIBV
	ASoC: amd: acp: add a null check for chip_pdev structure
	ASoC: amd: acp: remove i2s configuration check in acp_i2s_probe()
	ASoC: fsl-asoc-card: set priv->pdev before using it
	net: dsa: microchip: fix initial port flush problem
	openvswitch: get related ct labels from its master if it is not confirmed
	mlxsw: spectrum_buffers: Fix memory corruptions on Spectrum-4 systems
	bpf: Fix overrunning reservations in ringbuf
	ibmvnic: Free any outstanding tx skbs during scrq reset
	net: phy: micrel: add Microchip KSZ 9477 to the device table
	net: dsa: microchip: use collision based back pressure mode
	ice: Rebuild TC queues on VSI queue reconfiguration
	xdp: Remove WARN() from __xdp_reg_mem_model()
	netfilter: fix undefined reference to 'netfilter_lwtunnel_*' when CONFIG_SYSCTL=n
	btrfs: use NOFS context when getting inodes during logging and log replay
	Fix race for duplicate reqsk on identical SYN
	ALSA: seq: Fix missing channel at encoding RPN/NRPN MIDI2 messages
	net: dsa: microchip: fix wrong register write when masking interrupt
	sparc: fix old compat_sys_select()
	sparc: fix compat recv/recvfrom syscalls
	parisc: use correct compat recv/recvfrom syscalls
	powerpc: restore some missing spu syscalls
	tcp: fix tcp_rcv_fastopen_synack() to enter TCP_CA_Loss for failed TFO
	ALSA: seq: Fix missing MSB in MIDI2 SPP conversion
	netfilter: nf_tables: fully validate NFT_DATA_VALUE on store to data registers
	net: mana: Fix possible double free in error handling path
	bpf: Take return from set_memory_ro() into account with bpf_prog_lock_ro()
	powerpc/bpf: rename powerpc64_jit_data to powerpc_jit_data
	powerpc/bpf: use bpf_jit_binary_pack_[alloc|finalize|free]
	bpf: Take return from set_memory_rox() into account with bpf_jit_binary_lock_ro()
	drm/panel: ilitek-ili9881c: Fix warning with GPIO controllers that sleep
	vduse: validate block features only with block devices
	vduse: Temporarily fail if control queue feature requested
	x86/fpu: Fix AMD X86_BUG_FXSAVE_LEAK fixup
	mtd: partitions: redboot: Added conversion of operands to a larger type
	wifi: ieee80211: check for NULL in ieee80211_mle_size_ok()
	bpf: Mark bpf prog stack with kmsan_unposion_memory in interpreter mode
	RDMA/restrack: Fix potential invalid address access
	net/iucv: Avoid explicit cpumask var allocation on stack
	net/dpaa2: Avoid explicit cpumask var allocation on stack
	crypto: ecdh - explicitly zeroize private_key
	ALSA: emux: improve patch ioctl data validation
	media: dvbdev: Initialize sbuf
	irqchip/loongson: Select GENERIC_IRQ_EFFECTIVE_AFF_MASK if SMP for IRQ_LOONGARCH_CPU
	soc: ti: wkup_m3_ipc: Send NULL dummy message instead of pointer message
	gfs2: Fix NULL pointer dereference in gfs2_log_flush
	drm/radeon/radeon_display: Decrease the size of allocated memory
	nvme: fixup comment for nvme RDMA Provider Type
	drm/panel: simple: Add missing display timing flags for KOE TX26D202VM0BWA
	gpio: davinci: Validate the obtained number of IRQs
	RISC-V: fix vector insn load/store width mask
	drm/amdgpu: Fix pci state save during mode-1 reset
	riscv: stacktrace: convert arch_stack_walk() to noinstr
	gpiolib: cdev: Disallow reconfiguration without direction (uAPI v1)
	randomize_kstack: Remove non-functional per-arch entropy filtering
	x86: stop playing stack games in profile_pc()
	parisc: use generic sys_fanotify_mark implementation
	Revert "MIPS: pci: lantiq: restore reset gpio polarity"
	pinctrl: qcom: spmi-gpio: drop broken pm8008 support
	ocfs2: fix DIO failure due to insufficient transaction credits
	nfs: drop the incorrect assertion in nfs_swap_rw()
	mm: fix incorrect vbq reference in purge_fragmented_block
	mmc: sdhci-pci-o2micro: Convert PCIBIOS_* return codes to errnos
	mmc: sdhci-brcmstb: check R1_STATUS for erase/trim/discard
	mmc: sdhci-pci: Convert PCIBIOS_* return codes to errnos
	mmc: sdhci: Do not invert write-protect twice
	mmc: sdhci: Do not lock spinlock around mmc_gpio_get_ro()
	iio: xilinx-ams: Don't include ams_ctrl_channels in scan_mask
	counter: ti-eqep: enable clock at probe
	kbuild: doc: Update default INSTALL_MOD_DIR from extra to updates
	kbuild: Fix build target deb-pkg: ln: failed to create hard link
	i2c: testunit: don't erase registers after STOP
	i2c: testunit: discard write requests while old command is running
	ata: libata-core: Fix null pointer dereference on error
	ata,scsi: libata-core: Do not leak memory for ata_port struct members
	iio: adc: ad7266: Fix variable checking bug
	iio: accel: fxls8962af: select IIO_BUFFER & IIO_KFIFO_BUF
	iio: chemical: bme680: Fix pressure value output
	iio: chemical: bme680: Fix calibration data variable
	iio: chemical: bme680: Fix overflows in compensate() functions
	iio: chemical: bme680: Fix sensor data read operation
	net: usb: ax88179_178a: improve link status logs
	usb: gadget: printer: SS+ support
	usb: gadget: printer: fix races against disable
	usb: musb: da8xx: fix a resource leak in probe()
	usb: atm: cxacru: fix endpoint checking in cxacru_bind()
	usb: dwc3: core: remove lock of otg mode during gadget suspend/resume to avoid deadlock
	usb: gadget: aspeed_udc: fix device address configuration
	usb: typec: ucsi: glink: fix child node release in probe function
	usb: ucsi: stm32: fix command completion handling
	usb: dwc3: core: Add DWC31 version 2.00a controller
	usb: dwc3: core: Workaround for CSR read timeout
	Revert "serial: core: only stop transmit when HW fifo is empty"
	serial: 8250_omap: Implementation of Errata i2310
	serial: imx: set receiver level before starting uart
	serial: core: introduce uart_port_tx_limited_flags()
	serial: bcm63xx-uart: fix tx after conversion to uart_port_tx_limited()
	ALSA: hda/realtek: fix mute/micmute LEDs don't work for EliteBook 645/665 G11.
	tty: mcf: MCF54418 has 10 UARTS
	net: can: j1939: Initialize unused data in j1939_send_one()
	net: can: j1939: recover socket queue on CAN bus error during BAM transmission
	net: can: j1939: enhanced error handling for tightly received RTS messages in xtp_rx_rts_session_new
	PCI/MSI: Fix UAF in msi_capability_init
	cpufreq: intel_pstate: Use HWP to initialize ITMT if CPPC is missing
	irqchip/loongson-eiointc: Use early_cpu_to_node() instead of cpu_to_node()
	cpu/hotplug: Fix dynstate assignment in __cpuhp_setup_state_cpuslocked()
	irqchip/loongson-liointc: Set different ISRs for different cores
	kbuild: Install dtb files as 0644 in Makefile.dtbinst
	sh: rework sync_file_range ABI
	btrfs: zoned: fix initial free space detection
	csky, hexagon: fix broken sys_sync_file_range
	hexagon: fix fadvise64_64 calling conventions
	drm/drm_file: Fix pid refcounting race
	drm/nouveau/dispnv04: fix null pointer dereference in nv17_tv_get_ld_modes
	drm/fbdev-dma: Only set smem_start is enable per module option
	drm/amdgpu: avoid using null object of framebuffer
	drm/i915/gt: Fix potential UAF by revoke of fence registers
	drm/nouveau/dispnv04: fix null pointer dereference in nv17_tv_get_hd_modes
	drm/amd/display: Send DP_TOTAL_LTTPR_CNT during detection if LTTPR is present
	drm/amdgpu/atomfirmware: fix parsing of vram_info
	batman-adv: Don't accept TT entries for out-of-spec VIDs
	can: mcp251xfd: fix infinite loop when xmit fails
	ata: ahci: Clean up sysfs file on error
	ata: libata-core: Fix double free on error
	ftruncate: pass a signed offset
	syscalls: fix compat_sys_io_pgetevents_time64 usage
	syscalls: fix sys_fanotify_mark prototype
	erofs: fix NULL dereference of dif->bdev_handle in fscache mode
	pwm: stm32: Refuse too small period requests
	Revert "cpufreq: amd-pstate: Fix the inconsistency in max frequency units"
	mm/page_alloc: Separate THP PCP into movable and non-movable categories
	arm64: dts: rockchip: Fix SD NAND and eMMC init on rk3308-rock-pi-s
	arm64: dts: rockchip: Rename LED related pinctrl nodes on rk3308-rock-pi-s
	arm64: dts: rockchip: Fix the value of `dlg,jack-det-rate` mismatch on rk3399-gru
	ARM: dts: rockchip: rk3066a: add #sound-dai-cells to hdmi node
	arm64: dts: rockchip: make poweroff(8) work on Radxa ROCK 5A
	arm64: dts: rockchip: fix PMIC interrupt pin on ROCK Pi E
	arm64: dts: rockchip: Add sound-dai-cells for RK3368
	cxl/region: Move cxl_dpa_to_region() work to the region driver
	cxl/region: Avoid null pointer dereference in region lookup
	cxl/region: check interleave capability
	serial: imx: only set receiver level if it is zero
	serial: 8250_omap: Fix Errata i2310 with RX FIFO level check
	tracing/net_sched: NULL pointer dereference in perf_trace_qdisc_reset()
	Linux 6.6.37

Change-Id: Ibe3b92471ba46a72a35e28a347f8213fc9989797
Signed-off-by: Greg Kroah-Hartman <gregkh@google.com>